### ISSUE TITLE
Crash when starting scan not in PoE 

### ISSUE THREAD

**Issue by egorzaderiy** [Elkosscom/poe_gwennen_gambler#1]
1. Open gambler app
2. Press scan button

OR

1. Open gambler app
2. Switch to other programm, not to PoE
3. Press scan button

**Comment by Elkosscom** [comment]
Thanks for the feedback, I have not included any kind of active window detection, so I'll include it in the next version.

**Comment by Elkosscom** [comment]
Fixed in 1.0, now runs only if Path of Exile window is active
