### ISSUE TITLE
Infinite search

### ISSUE THREAD

**Issue by egorzaderiy** [Elkosscom/poe_gwennen_gambler#5]
Sometimes app can't finish the search and starts over after scanning bottom-right corner of items grid.

It happens if you just press hothey to search, need to press it from 2 to 7 times consecutively.

**Comment by Elkosscom** [comment]
I thought it was my crap keyboard that was playing. If it loops again, the temporary workaround is to press the hotkey again and it will stop. I'll have a look how to fix it permanently.

**Comment by Elkosscom** [comment]
Issue fixed in 1.3, closing
